---
title: "linear_models_4"
author: "Courtney Horn"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
require(lmerTest)
require(lmtest)
library(tidyverse)
library(corrplot)
library(htmltools)
library(agricolae)
#install.packages("MuMIn")
library(MuMIn)

```


```{r exploring variables of interest for Generalized Linear Models}
traitdata_subset <- select(trait_data2, logFruitLength:logSLA, Predicted, slope, aspect, lat, long)
lemur_density_Corr <- cor(traitdata_subset)
corrplot(lemur_density_Corr, method = "ellipse")
#the correlation plot matrix indicates that there are slight positive correlations between our response variable (Predicted) and multiple explanatory variables. There appear to be weak positive correlations between Predicted and logFruitLength, logFruitWidth, logSeedLength, logSeedWidth, logNitrogen, logSLA, slope, and long. The ones that appear to have the strongest positive correlations are logFruitLength, logNitrogen, slope, and longitude.
#The correlation plot matrix further indicates weak negative correlations between Predicted and logProtein and logNitrogen.
```
```{r exploring relationships between variables with ggplots}
#I made this plot to visually explore the relationship between some of fruit trait variables that stood out in the correlation plot matrix
Fruit_trait_plot <- ggplot(traitdata_subset, aes(x = logFruitLength, y = Predicted, color = logNitrogen)) +
  geom_point()
print(Fruit_trait_plot)
#This graph doesn't really display a relationship between logFruitLength and Predicted. It does indicate a relationship between logFruitLength and logNitrogen. There also are groupings of fruit lengths.

Fruit_trait_nutrient_plot <- ggplot(traitdata_subset, aes(x = logSugar, y = Predicted, color = logProtein)) +
  geom_point()
print(Fruit_trait_nutrient_plot)
#The graph doesn't really display a relationship between logSugar and Predicted
#There appears the be a relationship between logSugar and logProtein

Fruit_trait_nutrient_plot2 <- ggplot(traitdata_subset, aes(x = logProtein, y = Predicted, color = logTannins)) +
  geom_point()
print(Fruit_trait_nutrient_plot2)
#The graph doesn't really display a relationship between the variables


#Specifically, we predict that a) lemur densities are negatively related to landscape roughness and slope and b) reward regulation causes positive relationships between animal densities and fruit nutrient contents.

```



```{r creating linear models with species and transect site as random variables}
#I am using generalized linear models to explore whether fruit and landscape variables of interest affect lemur density
#This is the full linear model with all of the variables of interest and Species and Transect_Site as random variables
#I decided not to use variable interactions, because they kept freezing my computer
#the null hypothesis of my GLM is that the independent variables have no effect on my dependent variable
#the alternative hypothesis of my GLM is that the at least one of the independant variables has an affects the dependant variable 

lmer_Species_TS1 <- lmer(data = trait_data2, Predicted ~ logSeedLength + logNitrogen + lat + logSeedWidth + logTannins + roughness + long + logSugar + logSLA + slope + Site + logFruitLength + logFat + aspect + logFruitWidth + logProtein + (1|Species) + (1|Transect_Site))
summary(lmer_Species_TS1)
```



```{r checking GLM assumptions of the initial model, echo=FALSE}
#GLMs are based on the assumptions that the data residuals approximate a normal distribution
#My linear models have both continuous and categorical explanatory variables, so there is an assumption for my data that the variance of the response variable is equal among the groups
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(lmer_Species_TS1)
par(mfrow = c(1,1))
#This is a residuals versus fitted plot
#there appears to be a balance of positive and negative residuals, which is a good sign
#However, there appears to be a strange pattern of three seperate lines with negative slopes

qqnorm(trait_data2$Predicted); qqline(trait_data2$Predicted)
#this qqplot provides information on the normality of the response variable Predicted
#The data doesn't follow a normal distribution that well, but I don't think its terrible

```


```{r Reducing the initial GLM using the step function}
summary(lmer_Species_TS1)
step(lmer_Species_TS1)
#the step found that Predicted ~ logNitrogen + lat + roughness + slope + Site + logFruitLength + logFruitWidth + (1 | Species) is the best model

step_model <- lmer(data = trait_data2, Predicted ~ logNitrogen + lat + roughness + slope + Site + logFruitLength + logFruitWidth + (1 | Species))
summary(step_model)
#the model generated by the step function found that logNitrogen, lat, roughness, slope, SiteMaharira, SiteMiararony, SiteValohoaka, SiteVohiparara, logFruitLength, and logFruitWidth are significant variables
```
```{r reducing the initial GLM manually and keeping two random variables}
summary(lmer_Species_TS1)

lmer_Species_TS2 <- update(lmer_Species_TS1,~.-logSLA)
summary(lmer_Species_TS2)
#the model still doesn't seem significant with (Pr(>|t|) of the intercept of the model = 0.96296)

lmer_Species_TS3 <- update(lmer_Species_TS2,~.-logSeedLength)
summary(lmer_Species_TS3)

lmer_Species_TS4 <- update(lmer_Species_TS3,~.-aspect)
summary(lmer_Species_TS4)

lmer_Species_TS5 <- update(lmer_Species_TS4,~.-logTannins)
summary(lmer_Species_TS5)

lmer_Species_TS6 <- update(lmer_Species_TS5,~.-logSeedWidth)
summary(lmer_Species_TS6)

lmer_Species_TS7 <- update(lmer_Species_TS6,~.-logProtein)
summary(lmer_Species_TS7)

lmer_Species_TS8 <- update(lmer_Species_TS7,~.-logFat)
summary(lmer_Species_TS8)

lmer_Species_TS9 <- update(lmer_Species_TS8,~.-logSugar)
summary(lmer_Species_TS9)

lmer_Species_TS10 <- update(lmer_Species_TS9,~.-long)
summary(lmer_Species_TS10)
#now the intercept is significant!
  #going to keep removing variables to figure out what gives me the best model

lmer_Species_TS11 <- update(lmer_Species_TS10,~.-SiteMiaranony)
summary(lmer_Species_TS11)
#the p value decreased
#hmm it didn't suceed in taking out site miaranony, so it is just the same model as lmer_Species_TS10

#now comparing the models I built manually
anova(lmer_Species_TS8, lmer_Species_TS9, lmer_Species_TS10)
#this seems to indicate that lmer_Species_TS10 is the best
AIC(lmer_Species_TS8, lmer_Species_TS9, lmer_Species_TS10)
#this indicates lmer_Species_TS10 is the best

summary(lmer_Species_TS8)
summary(lmer_Species_TS9)
summary(lmer_Species_TS10)
#I think I would select TS10 because all of the variables are significant in those models
#TS10 has logNitrogen, lat, roughness, slope, SiteMaharira, Site Miaranony, SiteValohoaka, SiteVohiparara, logFruitLength, and logFruitWidth as significant variables
lrtest(lmer_Species_TS10, lmer_Species_TS9)
r.squaredGLMM(lmer_Species_TS10)
#this indicates that 10% of the variance is explained by fixed effects, while 46% of the variance is explained by the whole model

r.squaredGLMM(step_model)
#the step model explains almost the exact same amount of variance

par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(lmer_Species_TS10)
par(mfrow = c(1,1))
#this plot doesn't seem like its improved since I reduced the model

#the only difference between the model I got after reducing and the model generated with the step function is that my model has Transect_Site as a random variable, while the model generated by the step function doesn't include the Transect_Site variable
```



```{r general linear models for individual species}
unique(trait_data2$Species)
summary(trait_data2$Species)

AL_subset <- filter(trait_data2, Species == "Avahi_laniger")
View(AL_subset)

AL_lm_1 <- lm(data = AL_subset, Predicted ~ logSeedLength + logNitrogen + lat + logSeedWidth + logTannins + roughness + long + logSugar + logSLA + slope + Site + logFruitLength + logFat + aspect + logFruitWidth + logProtein)
summary(AL_lm_1)

AL_lm_site <- lm(data = AL_subset, Predicted ~ Site)
summary(AL_lm_site)
#My null hypothesis is that the mean density of the Avahi laniger species is equal at each site. My alternative hypothesis states that the mean density of the Avahi laniger species is not equal at each site
#Due to the significant p value of the model, I can reject the null hypothesis and accept the alternative hypothesis which states that the mean densities of Avahi laniger at the sites are not all equal

AL_lm_2 <- update(AL_lm_1,~.-logSugar)
summary(AL_lm_2)

AL_lm_3 <- update(AL_lm_2,~.-logTannins)
summary(AL_lm_3)

AL_lm_4 <- update(AL_lm_3,~.-aspect)
summary(AL_lm_4)

AL_lm_5 <- update(AL_lm_4,~.-logNitrogen)
summary(AL_lm_5)

AL_lm_6 <- update(AL_lm_5,~.-roughness)
summary(AL_lm_6)

AL_lm_7 <- update(AL_lm_6,~.-slope)
summary(AL_lm_7)

AL_lm_8 <- update(AL_lm_7,~.-logProtein)
summary(AL_lm_8)

AL_lm_9 <- update(AL_lm_8,~.-logFat)
summary(AL_lm_9)

AL_lm_10 <- update(AL_lm_9,~.-long)
summary(AL_lm_10)

AIC(AL_lm_2, AL_lm_3, AL_lm_4, AL_lm_5, AL_lm_6, AL_lm_7, AL_lm_8, AL_lm_9, AL_lm_10)
#AL_lm_7 is the best model, and explains 82% of the variation of Avahi laniger densities 

summary(AL_lm_7)
#logseedlength, lat, logseedwidth, long, logSLA, SiteMaharira, SiteMiararony, SiteValohoaka, SiteVohiparara, logFruitLength, logFat, logFruitWidth, and logProtein are significant


```


